alias Flagguesserapp.Flags.Flag
alias Flagguesserapp.Repo

[
  %Flag{name: "Afghanistan", continent: "Asia", image_path: "/images/af.svg"},
  %Flag{name: "Albania", continent: "Europe", image_path: "/images/al.svg"},
  %Flag{name: "Algeria", continent: "Africa", image_path: "/images/dz.svg"},
  %Flag{name: "Andorra", continent: "Europe", image_path: "/images/ad.svg"},
  %Flag{name: "Angola", continent: "Africa", image_path: "/images/ao.svg"},
  %Flag{name: "Antigua and Barbuda", continent: "North America", image_path: "/images/ag.svg"},
  %Flag{name: "Argentina", continent: "South America", image_path: "/images/ar.svg"},
  %Flag{name: "Armenia", continent: "Asia", image_path: "/images/am.svg"},
  %Flag{name: "Australia", continent: "Oceania", image_path: "/images/au.svg"},
  %Flag{name: "Austria", continent: "Europe", image_path: "/images/at.svg"},
  %Flag{name: "Azerbaijan", continent: "Asia", image_path: "/images/az.svg"},
  %Flag{name: "Bahamas", continent: "North America", image_path: "/images/bs.svg"},
  %Flag{name: "Bahrain", continent: "Asia", image_path: "/images/bh.svg"},
  %Flag{name: "Bangladesh", continent: "Asia", image_path: "/images/bd.svg"},
  %Flag{name: "Barbados", continent: "North America", image_path: "/images/bb.svg"},
  %Flag{name: "Belarus", continent: "Europe", image_path: "/images/by.svg"},
  %Flag{name: "Belgium", continent: "Europe", image_path: "/images/be.svg"},
  %Flag{name: "Belize", continent: "North America", image_path: "/images/bz.svg"},
  %Flag{name: "Benin", continent: "Africa", image_path: "/images/bj.svg"},
  %Flag{name: "Bhutan", continent: "Asia", image_path: "/images/bt.svg"},
  %Flag{name: "Bolivia", continent: "South America", image_path: "/images/bo.svg"},
  %Flag{name: "Bosnia and Herzegovina", continent: "Europe", image_path: "/images/ba.svg"},
  %Flag{name: "Botswana", continent: "Africa", image_path: "/images/bw.svg"},
  %Flag{name: "Brazil", continent: "South America", image_path: "/images/br.svg"},
  %Flag{name: "Brunei Darussalam", continent: "Asia", image_path: "/images/bn.svg"},
  %Flag{name: "Bulgaria", continent: "Europe", image_path: "/images/bg.svg"},
  %Flag{name: "Burkina Faso", continent: "Africa", image_path: "/images/bf.svg"},
  %Flag{name: "Burundi", continent: "Africa", image_path: "/images/bi.svg"},
  %Flag{name: "Cabo Verde", continent: "Africa", image_path: "/images/cv.svg"},
  %Flag{name: "Cambodia", continent: "Asia", image_path: "/images/kh.svg"},
  %Flag{name: "Cameroon", continent: "Africa", image_path: "/images/cm.svg"},
  %Flag{name: "Canada", continent: "North America", image_path: "/images/ca.svg"},
  %Flag{name: "Central African Republic", continent: "Africa", image_path: "/images/cf.svg"},
  %Flag{name: "Chad", continent: "Africa", image_path: "/images/td.svg"},
  %Flag{name: "Chile", continent: "South America", image_path: "/images/cl.svg"},
  %Flag{name: "China", continent: "Asia", image_path: "/images/cn.svg"},
  %Flag{name: "Colombia", continent: "South America", image_path: "/images/co.svg"},
  %Flag{name: "Comoros", continent: "Africa", image_path: "/images/km.svg"},
  %Flag{name: "Congo (Congo-Brazzaville)", continent: "Africa", image_path: "/images/cg.svg"},
  %Flag{name: "Congo (Democratic Republic)", continent: "Africa", image_path: "/images/cd.svg"},
  %Flag{name: "Costa Rica", continent: "North America", image_path: "/images/cr.svg"},
  %Flag{name: "Croatia", continent: "Europe", image_path: "/images/hr.svg"},
  %Flag{name: "Cuba", continent: "North America", image_path: "/images/cu.svg"},
  %Flag{name: "Cyprus", continent: "Europe", image_path: "/images/cy.svg"},
  %Flag{name: "Czechia (Czech Republic)", continent: "Europe", image_path: "/images/cz.svg"},
  %Flag{name: "Denmark", continent: "Europe", image_path: "/images/dk.svg"},
  %Flag{name: "Djibouti", continent: "Africa", image_path: "/images/dj.svg"},
  %Flag{name: "Dominica", continent: "North America", image_path: "/images/dm.svg"},
  %Flag{name: "Dominican Republic", continent: "North America", image_path: "/images/do.svg"},
  %Flag{name: "Ecuador", continent: "South America", image_path: "/images/ec.svg"},
  %Flag{name: "Egypt", continent: "Africa", image_path: "/images/eg.svg"},
  %Flag{name: "El Salvador", continent: "North America", image_path: "/images/sv.svg"},
  %Flag{name: "Equatorial Guinea", continent: "Africa", image_path: "/images/gq.svg"},
  %Flag{name: "Eritrea", continent: "Africa", image_path: "/images/er.svg"},
  %Flag{name: "Estonia", continent: "Europe", image_path: "/images/ee.svg"},
  %Flag{name: "Eswatini (Swaziland)", continent: "Africa", image_path: "/images/sz.svg"},
  %Flag{name: "Ethiopia", continent: "Africa", image_path: "/images/et.svg"},
  %Flag{name: "Fiji", continent: "Oceania", image_path: "/images/fj.svg"},
  %Flag{name: "Finland", continent: "Europe", image_path: "/images/fi.svg"},
  %Flag{name: "France", continent: "Europe", image_path: "/images/fr.svg"},
  %Flag{name: "Gabon", continent: "Africa", image_path: "/images/ga.svg"},
  %Flag{name: "Gambia", continent: "Africa", image_path: "/images/gm.svg"},
  %Flag{name: "Georgia", continent: "Asia", image_path: "/images/ge.svg"},
  %Flag{name: "Germany", continent: "Europe", image_path: "/images/de.svg"},
  %Flag{name: "Ghana", continent: "Africa", image_path: "/images/gh.svg"},
  %Flag{name: "Greece", continent: "Europe", image_path: "/images/gr.svg"},
  %Flag{name: "Grenada", continent: "North America", image_path: "/images/gd.svg"},
  %Flag{name: "Guatemala", continent: "North America", image_path: "/images/gt.svg"},
  %Flag{name: "Guinea", continent: "Africa", image_path: "/images/gn.svg"},
  %Flag{name: "Guinea-Bissau", continent: "Africa", image_path: "/images/gw.svg"},
  %Flag{name: "Guyana", continent: "South America", image_path: "/images/gy.svg"},
  %Flag{name: "Haiti", continent: "North America", image_path: "/images/ht.svg"},
  %Flag{name: "Honduras", continent: "North America", image_path: "/images/hn.svg"},
  %Flag{name: "Hungary", continent: "Europe", image_path: "/images/hu.svg"},
  %Flag{name: "Iceland", continent: "Europe", image_path: "/images/is.svg"},
  %Flag{name: "India", continent: "Asia", image_path: "/images/in.svg"},
  %Flag{name: "Indonesia", continent: "Asia", image_path: "/images/id.svg"},
  %Flag{name: "Iran", continent: "Asia", image_path: "/images/ir.svg"},
  %Flag{name: "Iraq", continent: "Asia", image_path: "/images/iq.svg"},
  %Flag{name: "Ireland", continent: "Europe", image_path: "/images/ie.svg"},
  %Flag{name: "Israel", continent: "Asia", image_path: "/images/il.svg"},
  %Flag{name: "Italy", continent: "Europe", image_path: "/images/it.svg"},
  %Flag{name: "Jamaica", continent: "North America", image_path: "/images/jm.svg"},
  %Flag{name: "Japan", continent: "Asia", image_path: "/images/jp.svg"},
  %Flag{name: "Jordan", continent: "Asia", image_path: "/images/jo.svg"},
  %Flag{name: "Kazakhstan", continent: "Asia", image_path: "/images/kz.svg"},
  %Flag{name: "Kenya", continent: "Africa", image_path: "/images/ke.svg"},
  %Flag{name: "Kiribati", continent: "Oceania", image_path: "/images/ki.svg"},
  %Flag{name: "Korea (North)", continent: "Asia", image_path: "/images/kp.svg"},
  %Flag{name: "Korea (South)", continent: "Asia", image_path: "/images/kr.svg"},
  %Flag{name: "Kosovo", continent: "Europe", image_path: "/images/xk.svg"},
  %Flag{name: "Kuwait", continent: "Asia", image_path: "/images/kw.svg"},
  %Flag{name: "Kyrgyzstan", continent: "Asia", image_path: "/images/kg.svg"},
  %Flag{name: "Laos", continent: "Asia", image_path: "/images/la.svg"},
  %Flag{name: "Latvia", continent: "Europe", image_path: "/images/lv.svg"},
  %Flag{name: "Lebanon", continent: "Asia", image_path: "/images/lb.svg"},
  %Flag{name: "Lesotho", continent: "Africa", image_path: "/images/ls.svg"},
  %Flag{name: "Liberia", continent: "Africa", image_path: "/images/lr.svg"},
  %Flag{name: "Libya", continent: "Africa", image_path: "/images/ly.svg"}
  # Füge weitere Länder alphabetisch hinzu...
]
|> Enum.each(&Repo.insert!/1)
